export interface Animal{
    id: number,
    commonName: string
    genre: string,
    species: string, //todo: genre + 
    isExtinct: boolean,
    currentPopulation: number, //todo: background based on the risk of extinction
    locations: string,
    imgUrl: string,
}

//todo: 3 extincted, 3 at high risk, 3 at low risk

export const animals = [
    {
        id: 1,
        commonName: 'Iberian Lynx',
        genre: 'Lynx',
        species: 'Pardinus',
        isExtinct: false,
        currentPopulation: 84,
        locations: 'Andalusia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 2,
        commonName: 'Dodo',
        genre: 'Lynx',
        species: ' pardinus',
        isExtinct: true,
        currentPopulation: 0,
        locations: 'Andalusia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 3,
        commonName: 'Panda',
        genre: 'Lynx',
        species: ' pardinus',
        isExtinct: false,
        currentPopulation: 84,
        locations: 'Australia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 4,
        commonName: 'Leopardo delle nevi',
        genre: 'Lynx',
        species: ' pardinus',
        isExtinct: false,
        currentPopulation: 840,
        locations: 'Australia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 5,
        commonName: 'White rhino',
        genre: 'Lynx',
        species: ' pardinus',
        isExtinct: true,
        currentPopulation: 84,
        locations: 'Andalusia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 6,
        commonName: 'Mosquito',
        genre: 'Lynx',
        species: ' pardinus',
        isExtinct: false,
        currentPopulation: 84,
        locations: 'Andalusia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 7,
        commonName: 'Foca Monaca',
        genre: 'Lynx',
        species: ' pardinus',
        isExtinct: false,
        currentPopulation: 84,
        locations: 'Andalusia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 8,
        commonName: 'Giava Tiger',
        genre: 'Lynx',
        species: ' pardinus',
        isExtinct: true,
        currentPopulation: 84,
        locations: 'Andalusia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 9,
        commonName: 'Condor',
        genre: 'Lynx',
        species: ' pardinus',
        isExtinct: false,
        currentPopulation: 84,
        locations: 'Andalusia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
];