export interface Animal{
    id: number,
    commonName: string
    genre: string,
    species: string,
    isExtinct: boolean,
    currentPopulation: number,
    locations: string,
    imgUrl: string,
}

export const animals = [
    {
        id: 1,
        commonName: 'Iberian Lynx',
        genre: 'Lynx',
        species: 'Pardinus',
        isExtinct: false,
        currentPopulation: 84,
        locations: 'Andalusia',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Linces19.jpg',
    },
    {
        id: 2,
        commonName: 'Dodo',
        genre: 'Raphus',
        species: 'Cucullatus',
        isExtinct: true,
        currentPopulation: 0,
        locations: 'Mauritius Island',
        imgUrl: 'http://www.mille-animali.com/images/animali/dodo.jpg',
    },
    {
        id: 3,
        commonName: 'Panda',
        genre: 'Ailuropoda',
        species: 'Melanoleuca',
        isExtinct: false,
        currentPopulation: 1864,
        locations: 'Southern China',
        imgUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/1200px-Grosser_Panda.JPG',
    },
    {
        id: 4,
        commonName: 'Snow leopard',
        genre: 'Panthera',
        species: 'Uncia',
        isExtinct: false,
        currentPopulation: 6590,
        locations: 'Central Asia Mountains',
        imgUrl: 'http://www.goasia.it/wp-content/uploads/sites/53/2018/02/snow-leopard-1972724_1920-750x500.jpg',
    },
    {
        id: 5,
        commonName: 'Nothern white rhinoceros',
        genre: 'Ceratotherium',
        species: 'Simum',
        isExtinct: true,
        currentPopulation: 0,
        locations: 'Center and outhern Africa',
        imgUrl: 'https://www.repstatic.it/content/nazionale/img/2020/06/16/201319665-b8cf8b3c-6038-4c06-992c-ed12db6f5514.jpg',
    },
    {
        id: 6,
        commonName: 'Mosquito',
        genre: 'Aedes',
        species: 'Aegypti',
        isExtinct: false,
        currentPopulation: 2_000_000,
        locations: 'Everywhere where\'s a pond and humid areas',
        imgUrl: 'https://www.focus.it/images/2021/10/21/zanzara-coreana_1020x680.jpg',
    },
    {
        id: 7,
        commonName: 'Mediterranean monk seal',
        genre: 'Monachus',
        species: 'Monachus',
        isExtinct: false,
        currentPopulation: 650,
        locations: 'Mediterranean sea',
        imgUrl: 'https://www.positizie.it/wp-content/uploads/2020/06/foca-monaca-e1593528812657.jpg',
    },
    {
        id: 8,
        commonName: 'Giava Tiger',
        genre: 'Panthera',
        species: 'Tigris - Sondaica',
        isExtinct: true,
        currentPopulation: 0,
        locations: 'Giava Island',
        imgUrl: 'https://rivistanatura.com/wp-content/uploads/2020/08/Panthera_tigris_virgata.jpg',
    },
    {
        id: 9,
        commonName: 'Condor',
        genre: 'Vultur',
        species: 'Gryphus',
        isExtinct: false,
        currentPopulation: 6700,
        locations: 'Andes mountains',
        imgUrl: 'https://images.everyeye.it/img-notizie/il-gigantesco-condor-ande-capace-volare-ore-sbattere-ali-v3-458538-1280x960.jpg',
    },
];